"""Add soft delete to jobs

Revision ID: 478d8d734be0
Revises: b65775f8ab3a
Create Date: 2026-08-17 12:40:36.094543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478d8d734be0'
down_revision: Union[str, Sequence[str], None] = 'b65775f8ab3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "jobs",
    sa.Column(
        "is_deleted",
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_deleted')
    # ### end Alembic commands ###
