"""Add description to skills

Revision ID: 9a1f2bfaa44b
Revises: 478d8d734be0
Create Date: 2026-08-17 17:15:02.781240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1f2bfaa44b'
down_revision: Union[str, Sequence[str], None] = '478d8d734be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'description')
    # ### end Alembic commands ###
