"""add pending_client_approval to job_status

Revision ID: e7f16b0d0ba6
Revises: 9a1f2bfaa44b
Create Date: 2026-08-20 16:36:46.090919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7f16b0d0ba6'
down_revision: Union[str, Sequence[str], None] = '9a1f2bfaa44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'status',
               existing_type=mysql.ENUM('open', 'assigned', 'in_progress', 'completed', 'closed'),
               type_=sa.Enum('open', 'assigned', 'in_progress', 'pending_client_approval', 'completed', 'closed', name='job_status'),
               existing_nullable=False)
    op.create_index('idx_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_user_created', table_name='notifications')
    op.alter_column('jobs', 'status',
               existing_type=sa.Enum('open', 'assigned', 'in_progress', 'pending_client_approval', 'completed', 'closed', name='job_status'),
               type_=mysql.ENUM('open', 'assigned', 'in_progress', 'completed', 'closed'),
               existing_nullable=False)
    # ### end Alembic commands ###
